services:
  dev:
    image: instagram_clone_nodejs-dev:latest
    build: .
    volumes:
      - ./node_modules:/www/node_modules
    ports:
      - "3000:3000"
    command: "npm run start:dev"
    develop:
      watch:
        - action: sync
          path: .
          target: /www